apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    io.kompose.service: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      labels:
        io.kompose.service: app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: django-app
          image: "cr.yandex/crpc042ndt01ecmkknem/app-django:latest"
          imagePullPolicy: Always
          command: ["/bin/sh","-c"]
          args: ["python manage.py migrate && python manage.py runserver 0.0.0.0:3003"]
          env:
            - name: DB_HOST
              value: postgres-db-postgresql.default.svc.cluster.local
            - name: DB_NAME
              value: tutorial-dev
            - name: DB_PASS
              value: password123
            - name: DB_USER
              value: vinhle
          ports:
            - name: http
              containerPort: 3003
              protocol: TCP
          # volumeMounts:
          #   - mountPath: /app
          #     name: app-mem
      nodeSelector: {}
      affinity: {}
      tolerations: []
      # volumes:
      #   - name: app-mem
      #     persistentVolumeClaim:
      #       claimName: app-mem
