name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build .
      
    - name: Push the Docker image
      run: docker login --username ${{ secrets.YD_USERNAME }} --password ${{ secrets.YD_TOKEN }} cr.yandex && docker push cr.yandex/${{ secrets.YD_REGISTRY }}/${{ secrets.YD_REPO }}:latest
      
