name: Helm

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Login to Docker Hub
      uses: addnab/docker-run-action@v3
      with:
        username: ${{ secrets.YD_USERNAME }}
        password: ${{ secrets.YD_TOKEN }}
        registry: cr.yandex
        image: cr.yandex/${{ secrets.YD_REGISTRY }}/${{ secrets.YD_REPO_HELM }}
        run: "helm upgrade --install --namespace default app-dj /usr/src/chart/my-django-app --debug"
