name: Helm

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: 'Deploy'
      uses: 'deliverybot/helm@master'
      with:
        release: 'app-dj'
        track: canary
        namespace: 'default'
        chart: 'app'
        token: '${{ github.token }}'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
