name: Helm

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.YD_USERNAME }}
        password: ${{ secrets.YD_TOKEN }}
        registry: cr.yandex

    - name: Docker pull
      run: docker pull cr.yandex/${{ secrets.YD_REGISTRY }}/${{ secrets.YD_REPO_HELM }}:latest

    - name: Helm test
      run: "docker run cr.yandex/${{ secrets.YD_REGISTRY }}/${{ secrets.YD_REPO_HELM }} \"helm upgrade --install --namespace default app-dj /usr/src/chart/my-django-app --debug\""
